# Generated by Django 3.1.7 on 2021-03-31 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210331_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartgame',
            old_name='product',
            new_name='game',
        ),
    ]
